### PR TITLE
fix: compression on event stream

### LINKED ISSUE #162: Disable compression for event stream response in node adapter
`app.use(compression({filter: (req) => req.headers['content-type']?.startsWith('text/event-stream')}))`

Similar issue found in remix: https://github.com/remix-run/remix/issues/3232

### PR DESCRIPTION
**Pull request by G3root**
fixes #162

### CODE REVIEW

File: test/event-stream-test.ts [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+                return;
+              }
+            },
+          });
+          return new Response(stream, {
+            headers: { "Content-Type": "text/event-stream" },
+          });
+        }
+        
+        export default () => {
```
Comment (nksaraf) [inline test/event-stream-test.ts:58]:
```suggestion
        export default function Page() {
```

Just for consistency with other tests

File: test/event-stream-test.ts [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+          let ref;
```
Comment (nksaraf) [inline test/event-stream-test.ts:59]: Do we need this `ref` stuff, can you do this with a signal again and see if it works, I think it will, and if it doesn't thats an issue too..

**Review by nksaraf — CHANGES_REQUESTED** [review]
Just a few small changes

File: test/event-stream-test.ts (hunk 2 above)
Comment (G3root) [reply test/event-stream-test.ts:59]: i ran the tests in Gitpod. using a signal seems to hang the playwright , when using a ref it work as expected.

**Comment by nksaraf** [comment]
Can you change your PR to point to `solidjs:dev` instead, we are staging changes there before pulling them in main
