### PR TITLE
fix: Add `ChunkReader`

### LINKED ISSUE #1243: [Bug?]: Seroval deserializeStream fails for large values
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have a solidstart app with two routes which each load 1-3 MB of nested JSON data in a server function. This data used to be serialized with `JSON.stringify` but since 0.4.0 has been replaced with seroval.

When I quickly navigate repeatedly between these two routes (and sometimes when preloading data onmousehover), sometimes I will encounter the following error
image
browsing up the stacktrace
image
the error originates inside code [introduced by a recent bugfix](https://github.com/solidjs/solid-start/pull/1131) to `deserializeStream`

 * When I print the current `split` that is deserialized (https://github.com/solidjs/solid-start/blob/main/packages/start/config/server-runtime.jsx#L46), I notice that it is an incomplete JS expression. This suggests the large value being serialized is somehow truncated by the `ReadableStream` before a newline is inserted.
 * Where this truncation occurs changes across trials.
 * Looking at network traffic, it appears the entire payload makes it across the wire. The bug is probably in solidstart's `deserializeStream`

### Expected behavior 🤔

I expect to be able to navigate between these routes without issue. This was the case prior to 0.4.x, and expected behavior is restored when I `pnpm link` a fork which removes seroval deserialization on server functions (https://github.com/solidjs/solid-start/compare/main...feynmanliang:solid-start:seroval-error-repro)

### Steps to reproduce 🕹

Steps: Issue occurs in proprietary app, I will create a stackblitz with minimal repro

1. Create two routes which have a `load` that serdes a very long quoted JS string from a server function
2. Navigate between the two routes rapidly
3. Sometimes, the `split` processed by `deserializeStream` is truncated and the closing quote is missing, leading to an error

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by lxsmnsyc**
- This PR adds the `ChunkReader` utility class.
  - The purpose of this class is for proper consumption of chunks that are being streamed by the server functions request. Previously, we only deserialize the first valid seroval chunk with the assumption that the first response chunk is a valid seroval chunk. However the browser interprets it differently, that is, if the chunk size is too large, the browser will split the "valid chunk" into smaller chunks, leading into a deserialization error.
  - `ChunkReader` ensures that the first chunk is a valid chunk. If it's invalid, it will attempt to read a new chunk, and check if part of the chunk is a valid seroval chunk. This process repeats until the stream is drained.
- Fixes #1243 

Test app:

```js
// @refresh reload
import { createEffect, createResource, createSignal } from "solid-js";
import "./app.css";

export default function App() {
  const [count, setCount] = createSignal(0);

  const [data] = createResource(count, async (value) => {
    "use server";

    return {
      data: new Promise((resolve) => {
        const giantData = [];
        for (let i = 0; i < 1000000; i++) {
          giantData.push(`index: ${i} value: ${value}`);
        }
        setTimeout(resolve, 1000, giantData);
      }),
    };
  });

  createEffect(() => {
    console.log(data()?.data);
  });

  return (
    <main>
      <h1>Hello world!</h1>
      <button class="increment" onClick={() => setCount(count() + 1)}>
        Clicks: {count()}
      </button>
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

> [!NOTE]
> In my test, the maximum chunk size is around 2097152 bytes. Tested in latest Arc (Chromium browser) on Mac OS

### CODE REVIEW

File: packages/start/config/server-runtime.jsx [hunk 1]
```diff
@@ -13,55 +13,100 @@ import {
...
+    // Get the first valid seroval chunk
+    const [first, ...rest] = this.buffer.split('\n');
+    // Deserialize the seroval chunk
+    const result = {
+      done: false,
+      value: deserialize(first),
+    };
+    // if it succeeds, remove the first valid chunk
+    // from the buffer
+    this.buffer = rest.join('\n');
```
Comment (feynmanliang) [inline packages/start/config/server-runtime.jsx:56]: `Array.shift` instead of split/destructure/join?

File: packages/start/config/server-runtime.jsx [hunk 2]
```diff
@@ -13,55 +13,100 @@ import {
...
+      return await this.nextValue();
+    } catch (error) {
+      // If it happens that there's an error again
+      // and we are done reading the buffer
+      // then the whole stream is invalid.
+      if (this.done) {
+        throw new Error('Malformed server function stream.');
       }
+      // Since it's invalid (some syntax-related issue)
+      // we read a new chunk, and hope there's a valid
```
Comment (feynmanliang) [inline packages/start/config/server-runtime.jsx:72]: I will test this tomorrow, but do we think this will fix #1245 where a single large JS expression is split across two chunks? AFAIK we need to concatenate the two partial chunks so that the entire chunk is a valid expression but I think ATM this code would drop both chunks?

File: packages/start/config/server-runtime.jsx (hunk 1 above)
Comment (lxsmnsyc) [reply packages/start/config/server-runtime.jsx:56]: I still needed to re-join it since buffer is a string.

File: packages/start/config/server-runtime.jsx (hunk 2 above)
Comment (lxsmnsyc) [reply packages/start/config/server-runtime.jsx:72]: I've already tested this with a gigantic chunk (as seen with the Test app). The idea is to keep reading until there's a valid seroval (JS) chunk.

Comment (feynmanliang) [reply packages/start/config/server-runtime.jsx:72]: Can you help explain to me? My understanding is that on an invalid chunk https://github.com/solidjs/solid-start/pull/1245/files#diff-d5889473d46bb02f0141e0e1dfa59c3c5c118a8e660eb941117bfc25fd3d1234R52 will throw and `first` will lose all references and be GCed.

Comment (lxsmnsyc) [reply packages/start/config/server-runtime.jsx:72]: Basically, when we call `deserialize` we are also trying to know if the `first` chunk is a valid seroval chunk. Once it deserializes successfully, we remove the `first` chunk from the `buffer`.

If `deserialize` fails then we move to the `catch` block. There we read the next Response chunk, and then attempt to deserialize again. Take note that the `buffer` only shrinks for every successful deserialize call.

We repeat this until a valid seroval chunk has been encountered and/or the response is done and the `buffer` is empty.

Comment (feynmanliang) [reply packages/start/config/server-runtime.jsx:72]: Thanks for helping me out, I get it now. A reader of L52 must be aware of exception handling on L68 in order to reason about correct behavior

**Comment by feynmanliang** [comment]
Really appreciate your help @lxsmnsyc getting this upstream :) Can confirm that this fixes #1243

File: packages/start/config/server-runtime.jsx (hunk 2 above)
Comment (lxsmnsyc) [reply packages/start/config/server-runtime.jsx:72]: TBF that thrown Error is unlikely to happen, I guess.

**Comment by ryansolid** [comment]
> Really appreciate your help @lxsmnsyc getting this upstream :) Can confirm that this fixes #1243

Awesome thanks for letting us know.
